[basic]
window_width = 1280.0
window_height = 720.0
debug = true

[sprite]
sprite_sheet_path = "sprites.png"
sprite_sheet_width = 8
sprite_sheet_height = 8
tile_w = 16
tile_h = 16

[world]
num_world_decorations = 500
world_width = 3000.0
world_height = 2500.0
background_color = [197, 204, 184]

[player]
health = 100.0
speed = 80.0
damage_cooldown = 0.30000001192092896
collider_size = 5.0

[enemy]
health = 100.0
speed = 40.0
damage = 10.0
damage_cooldown = 0.15000000596046448
follow_range = 200.0
collider_size = 6.0
spawn_limit = 20000
spawn_rate_per_second = 500
spawn_interval = 1.0

[bullet]
damage = 20.0
speed = 600.0
spawn_interval = 0.10000000149011612
lifetime = 0.5
num_per_shot = 10
